### ISSUE TITLE
No email 

### ISSUE THREAD

**Issue by ibuziuk** [AlinaPezkina/Juicer-by-AlinaPezkina#1]
Please, add email to your repository. 
Do you still have the maven issue? It might be coupled with some windows security settings - try to disable everything suspicious. Anyway, I have created project for you in case you want be able to tackle the problem - https://www.dropbox.com/sh/e0xcrbuamrjhcg3/AADZuNd0B9Xtnwdcu6iYqDTIa/WebChatApplication.zip?dl=0
Try to download and execute "mvn clean package" in the root of the project. .war file should be created in the target folder. Hope it would help.

**Comment by Alina-Yaroshina** [comment]
I found out, that the problem occurred because of the antivirus, which has blocked maven and created all the files in the hidden folder in its sand-box. Anyway, thank you so much for your help.

**Comment by ibuziuk** [comment]
Oh, great! closing the issue
